on: push
name: Example Workflow
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LD_ACCESS_TOKEN: ${{ secrets.LD_ACCESS_TOKEN }}
        LD_PROJ_KEY: YOUR_PROJECT_KEY
